# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2017-win2016'

steps:
  - powershell: ./Setup-MongoDB.ps1
    displayName: 'Setup MongoDB'

  - powershell: ./build.ps1
    displayName: 'Cake build'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1