# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreInstaller@2
    inputs:
      useGlobalJson: true
      
  - task: Bash@3
    displayName: 'Run MongoDB'
    inputs:
      targetType: 'inline'
      script: docker run -d -p 27017:27017 mongo:latest

  - powershell: ./build.ps1
    displayName: 'Cake build'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1