# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreInstaller@2
    inputs:
      useGlobalJson: true
      
  - bash: docker run -d -p 27017:27017 mongo:latest
  - bash: dotnet restore
  - bash: dotnet build --configuration Release --no-restore
  - bash: dotnet test --configuration Release --no-build --logger trx
  - bash: dotnet publish --configuration Release --no-build
  - bash: cd ./src/ParkrunMap.FunctionsApp/bin/Release/net6.0/publish/; zip -r "$BUILD_ARTIFACTSTAGINGDIRECTORY/ParkrunMap.FunctionsApp.zip" * 

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1